# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liuky/RDMA/Test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liuky/RDMA/Test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liuky/RDMA/Test/CMakeFiles /home/liuky/RDMA/Test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liuky/RDMA/Test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rdma_send_test

# Build rule for target.
rdma_send_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_send_test
.PHONY : rdma_send_test

# fast build rule for target.
rdma_send_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_send_test.dir/build.make CMakeFiles/rdma_send_test.dir/build
.PHONY : rdma_send_test/fast

#=============================================================================
# Target rules for targets named rdma_write_test

# Build rule for target.
rdma_write_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_write_test
.PHONY : rdma_write_test

# fast build rule for target.
rdma_write_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_write_test.dir/build.make CMakeFiles/rdma_write_test.dir/build
.PHONY : rdma_write_test/fast

#=============================================================================
# Target rules for targets named rdma_read_test

# Build rule for target.
rdma_read_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_read_test
.PHONY : rdma_read_test

# fast build rule for target.
rdma_read_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_read_test.dir/build.make CMakeFiles/rdma_read_test.dir/build
.PHONY : rdma_read_test/fast

#=============================================================================
# Target rules for targets named rdma_atomic_test

# Build rule for target.
rdma_atomic_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_atomic_test
.PHONY : rdma_atomic_test

# fast build rule for target.
rdma_atomic_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_atomic_test.dir/build.make CMakeFiles/rdma_atomic_test.dir/build
.PHONY : rdma_atomic_test/fast

#=============================================================================
# Target rules for targets named rdma_cm_client

# Build rule for target.
rdma_cm_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_cm_client
.PHONY : rdma_cm_client

# fast build rule for target.
rdma_cm_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_client.dir/build.make CMakeFiles/rdma_cm_client.dir/build
.PHONY : rdma_cm_client/fast

#=============================================================================
# Target rules for targets named rdma_cm_server

# Build rule for target.
rdma_cm_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_cm_server
.PHONY : rdma_cm_server

# fast build rule for target.
rdma_cm_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_server.dir/build.make CMakeFiles/rdma_cm_server.dir/build
.PHONY : rdma_cm_server/fast

#=============================================================================
# Target rules for targets named rdma_client

# Build rule for target.
rdma_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_client
.PHONY : rdma_client

# fast build rule for target.
rdma_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/build
.PHONY : rdma_client/fast

#=============================================================================
# Target rules for targets named rdma_server

# Build rule for target.
rdma_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_server
.PHONY : rdma_server

# fast build rule for target.
rdma_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/build
.PHONY : rdma_server/fast

#=============================================================================
# Target rules for targets named ibv_devices

# Build rule for target.
ibv_devices: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ibv_devices
.PHONY : ibv_devices

# fast build rule for target.
ibv_devices/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ibv_devices.dir/build.make CMakeFiles/ibv_devices.dir/build
.PHONY : ibv_devices/fast

#=============================================================================
# Target rules for targets named ibv_devinfo

# Build rule for target.
ibv_devinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ibv_devinfo
.PHONY : ibv_devinfo

# fast build rule for target.
ibv_devinfo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ibv_devinfo.dir/build.make CMakeFiles/ibv_devinfo.dir/build
.PHONY : ibv_devinfo/fast

src/common/common.o: src/common/common.c.o
.PHONY : src/common/common.o

# target to build an object file
src/common/common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_send_test.dir/build.make CMakeFiles/rdma_send_test.dir/src/common/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_write_test.dir/build.make CMakeFiles/rdma_write_test.dir/src/common/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_read_test.dir/build.make CMakeFiles/rdma_read_test.dir/src/common/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_atomic_test.dir/build.make CMakeFiles/rdma_atomic_test.dir/src/common/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/src/common/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/src/common/common.c.o
.PHONY : src/common/common.c.o

src/common/common.i: src/common/common.c.i
.PHONY : src/common/common.i

# target to preprocess a source file
src/common/common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_send_test.dir/build.make CMakeFiles/rdma_send_test.dir/src/common/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_write_test.dir/build.make CMakeFiles/rdma_write_test.dir/src/common/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_read_test.dir/build.make CMakeFiles/rdma_read_test.dir/src/common/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_atomic_test.dir/build.make CMakeFiles/rdma_atomic_test.dir/src/common/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/src/common/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/src/common/common.c.i
.PHONY : src/common/common.c.i

src/common/common.s: src/common/common.c.s
.PHONY : src/common/common.s

# target to generate assembly for a file
src/common/common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_send_test.dir/build.make CMakeFiles/rdma_send_test.dir/src/common/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_write_test.dir/build.make CMakeFiles/rdma_write_test.dir/src/common/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_read_test.dir/build.make CMakeFiles/rdma_read_test.dir/src/common/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_atomic_test.dir/build.make CMakeFiles/rdma_atomic_test.dir/src/common/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/src/common/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/src/common/common.c.s
.PHONY : src/common/common.c.s

src/common/rdma_common.o: src/common/rdma_common.c.o
.PHONY : src/common/rdma_common.o

# target to build an object file
src/common/rdma_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_client.dir/build.make CMakeFiles/rdma_cm_client.dir/src/common/rdma_common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_server.dir/build.make CMakeFiles/rdma_cm_server.dir/src/common/rdma_common.c.o
.PHONY : src/common/rdma_common.c.o

src/common/rdma_common.i: src/common/rdma_common.c.i
.PHONY : src/common/rdma_common.i

# target to preprocess a source file
src/common/rdma_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_client.dir/build.make CMakeFiles/rdma_cm_client.dir/src/common/rdma_common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_server.dir/build.make CMakeFiles/rdma_cm_server.dir/src/common/rdma_common.c.i
.PHONY : src/common/rdma_common.c.i

src/common/rdma_common.s: src/common/rdma_common.c.s
.PHONY : src/common/rdma_common.s

# target to generate assembly for a file
src/common/rdma_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_client.dir/build.make CMakeFiles/rdma_cm_client.dir/src/common/rdma_common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_server.dir/build.make CMakeFiles/rdma_cm_server.dir/src/common/rdma_common.c.s
.PHONY : src/common/rdma_common.c.s

src/device/ibv_devices_test.o: src/device/ibv_devices_test.c.o
.PHONY : src/device/ibv_devices_test.o

# target to build an object file
src/device/ibv_devices_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ibv_devices.dir/build.make CMakeFiles/ibv_devices.dir/src/device/ibv_devices_test.c.o
.PHONY : src/device/ibv_devices_test.c.o

src/device/ibv_devices_test.i: src/device/ibv_devices_test.c.i
.PHONY : src/device/ibv_devices_test.i

# target to preprocess a source file
src/device/ibv_devices_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ibv_devices.dir/build.make CMakeFiles/ibv_devices.dir/src/device/ibv_devices_test.c.i
.PHONY : src/device/ibv_devices_test.c.i

src/device/ibv_devices_test.s: src/device/ibv_devices_test.c.s
.PHONY : src/device/ibv_devices_test.s

# target to generate assembly for a file
src/device/ibv_devices_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ibv_devices.dir/build.make CMakeFiles/ibv_devices.dir/src/device/ibv_devices_test.c.s
.PHONY : src/device/ibv_devices_test.c.s

src/device/ibv_devinfo_test.o: src/device/ibv_devinfo_test.c.o
.PHONY : src/device/ibv_devinfo_test.o

# target to build an object file
src/device/ibv_devinfo_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ibv_devinfo.dir/build.make CMakeFiles/ibv_devinfo.dir/src/device/ibv_devinfo_test.c.o
.PHONY : src/device/ibv_devinfo_test.c.o

src/device/ibv_devinfo_test.i: src/device/ibv_devinfo_test.c.i
.PHONY : src/device/ibv_devinfo_test.i

# target to preprocess a source file
src/device/ibv_devinfo_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ibv_devinfo.dir/build.make CMakeFiles/ibv_devinfo.dir/src/device/ibv_devinfo_test.c.i
.PHONY : src/device/ibv_devinfo_test.c.i

src/device/ibv_devinfo_test.s: src/device/ibv_devinfo_test.c.s
.PHONY : src/device/ibv_devinfo_test.s

# target to generate assembly for a file
src/device/ibv_devinfo_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ibv_devinfo.dir/build.make CMakeFiles/ibv_devinfo.dir/src/device/ibv_devinfo_test.c.s
.PHONY : src/device/ibv_devinfo_test.c.s

src/req_test/atomic_test.o: src/req_test/atomic_test.c.o
.PHONY : src/req_test/atomic_test.o

# target to build an object file
src/req_test/atomic_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_atomic_test.dir/build.make CMakeFiles/rdma_atomic_test.dir/src/req_test/atomic_test.c.o
.PHONY : src/req_test/atomic_test.c.o

src/req_test/atomic_test.i: src/req_test/atomic_test.c.i
.PHONY : src/req_test/atomic_test.i

# target to preprocess a source file
src/req_test/atomic_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_atomic_test.dir/build.make CMakeFiles/rdma_atomic_test.dir/src/req_test/atomic_test.c.i
.PHONY : src/req_test/atomic_test.c.i

src/req_test/atomic_test.s: src/req_test/atomic_test.c.s
.PHONY : src/req_test/atomic_test.s

# target to generate assembly for a file
src/req_test/atomic_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_atomic_test.dir/build.make CMakeFiles/rdma_atomic_test.dir/src/req_test/atomic_test.c.s
.PHONY : src/req_test/atomic_test.c.s

src/req_test/rdma_client.o: src/req_test/rdma_client.c.o
.PHONY : src/req_test/rdma_client.o

# target to build an object file
src/req_test/rdma_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/src/req_test/rdma_client.c.o
.PHONY : src/req_test/rdma_client.c.o

src/req_test/rdma_client.i: src/req_test/rdma_client.c.i
.PHONY : src/req_test/rdma_client.i

# target to preprocess a source file
src/req_test/rdma_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/src/req_test/rdma_client.c.i
.PHONY : src/req_test/rdma_client.c.i

src/req_test/rdma_client.s: src/req_test/rdma_client.c.s
.PHONY : src/req_test/rdma_client.s

# target to generate assembly for a file
src/req_test/rdma_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_client.dir/build.make CMakeFiles/rdma_client.dir/src/req_test/rdma_client.c.s
.PHONY : src/req_test/rdma_client.c.s

src/req_test/rdma_cm/rdma_cm_client.o: src/req_test/rdma_cm/rdma_cm_client.c.o
.PHONY : src/req_test/rdma_cm/rdma_cm_client.o

# target to build an object file
src/req_test/rdma_cm/rdma_cm_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_client.dir/build.make CMakeFiles/rdma_cm_client.dir/src/req_test/rdma_cm/rdma_cm_client.c.o
.PHONY : src/req_test/rdma_cm/rdma_cm_client.c.o

src/req_test/rdma_cm/rdma_cm_client.i: src/req_test/rdma_cm/rdma_cm_client.c.i
.PHONY : src/req_test/rdma_cm/rdma_cm_client.i

# target to preprocess a source file
src/req_test/rdma_cm/rdma_cm_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_client.dir/build.make CMakeFiles/rdma_cm_client.dir/src/req_test/rdma_cm/rdma_cm_client.c.i
.PHONY : src/req_test/rdma_cm/rdma_cm_client.c.i

src/req_test/rdma_cm/rdma_cm_client.s: src/req_test/rdma_cm/rdma_cm_client.c.s
.PHONY : src/req_test/rdma_cm/rdma_cm_client.s

# target to generate assembly for a file
src/req_test/rdma_cm/rdma_cm_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_client.dir/build.make CMakeFiles/rdma_cm_client.dir/src/req_test/rdma_cm/rdma_cm_client.c.s
.PHONY : src/req_test/rdma_cm/rdma_cm_client.c.s

src/req_test/rdma_cm/rdma_cm_server.o: src/req_test/rdma_cm/rdma_cm_server.c.o
.PHONY : src/req_test/rdma_cm/rdma_cm_server.o

# target to build an object file
src/req_test/rdma_cm/rdma_cm_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_server.dir/build.make CMakeFiles/rdma_cm_server.dir/src/req_test/rdma_cm/rdma_cm_server.c.o
.PHONY : src/req_test/rdma_cm/rdma_cm_server.c.o

src/req_test/rdma_cm/rdma_cm_server.i: src/req_test/rdma_cm/rdma_cm_server.c.i
.PHONY : src/req_test/rdma_cm/rdma_cm_server.i

# target to preprocess a source file
src/req_test/rdma_cm/rdma_cm_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_server.dir/build.make CMakeFiles/rdma_cm_server.dir/src/req_test/rdma_cm/rdma_cm_server.c.i
.PHONY : src/req_test/rdma_cm/rdma_cm_server.c.i

src/req_test/rdma_cm/rdma_cm_server.s: src/req_test/rdma_cm/rdma_cm_server.c.s
.PHONY : src/req_test/rdma_cm/rdma_cm_server.s

# target to generate assembly for a file
src/req_test/rdma_cm/rdma_cm_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_cm_server.dir/build.make CMakeFiles/rdma_cm_server.dir/src/req_test/rdma_cm/rdma_cm_server.c.s
.PHONY : src/req_test/rdma_cm/rdma_cm_server.c.s

src/req_test/rdma_server.o: src/req_test/rdma_server.c.o
.PHONY : src/req_test/rdma_server.o

# target to build an object file
src/req_test/rdma_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/src/req_test/rdma_server.c.o
.PHONY : src/req_test/rdma_server.c.o

src/req_test/rdma_server.i: src/req_test/rdma_server.c.i
.PHONY : src/req_test/rdma_server.i

# target to preprocess a source file
src/req_test/rdma_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/src/req_test/rdma_server.c.i
.PHONY : src/req_test/rdma_server.c.i

src/req_test/rdma_server.s: src/req_test/rdma_server.c.s
.PHONY : src/req_test/rdma_server.s

# target to generate assembly for a file
src/req_test/rdma_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_server.dir/build.make CMakeFiles/rdma_server.dir/src/req_test/rdma_server.c.s
.PHONY : src/req_test/rdma_server.c.s

src/req_test/read_test.o: src/req_test/read_test.c.o
.PHONY : src/req_test/read_test.o

# target to build an object file
src/req_test/read_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_read_test.dir/build.make CMakeFiles/rdma_read_test.dir/src/req_test/read_test.c.o
.PHONY : src/req_test/read_test.c.o

src/req_test/read_test.i: src/req_test/read_test.c.i
.PHONY : src/req_test/read_test.i

# target to preprocess a source file
src/req_test/read_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_read_test.dir/build.make CMakeFiles/rdma_read_test.dir/src/req_test/read_test.c.i
.PHONY : src/req_test/read_test.c.i

src/req_test/read_test.s: src/req_test/read_test.c.s
.PHONY : src/req_test/read_test.s

# target to generate assembly for a file
src/req_test/read_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_read_test.dir/build.make CMakeFiles/rdma_read_test.dir/src/req_test/read_test.c.s
.PHONY : src/req_test/read_test.c.s

src/req_test/send_test.o: src/req_test/send_test.c.o
.PHONY : src/req_test/send_test.o

# target to build an object file
src/req_test/send_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_send_test.dir/build.make CMakeFiles/rdma_send_test.dir/src/req_test/send_test.c.o
.PHONY : src/req_test/send_test.c.o

src/req_test/send_test.i: src/req_test/send_test.c.i
.PHONY : src/req_test/send_test.i

# target to preprocess a source file
src/req_test/send_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_send_test.dir/build.make CMakeFiles/rdma_send_test.dir/src/req_test/send_test.c.i
.PHONY : src/req_test/send_test.c.i

src/req_test/send_test.s: src/req_test/send_test.c.s
.PHONY : src/req_test/send_test.s

# target to generate assembly for a file
src/req_test/send_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_send_test.dir/build.make CMakeFiles/rdma_send_test.dir/src/req_test/send_test.c.s
.PHONY : src/req_test/send_test.c.s

src/req_test/write_test.o: src/req_test/write_test.c.o
.PHONY : src/req_test/write_test.o

# target to build an object file
src/req_test/write_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_write_test.dir/build.make CMakeFiles/rdma_write_test.dir/src/req_test/write_test.c.o
.PHONY : src/req_test/write_test.c.o

src/req_test/write_test.i: src/req_test/write_test.c.i
.PHONY : src/req_test/write_test.i

# target to preprocess a source file
src/req_test/write_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_write_test.dir/build.make CMakeFiles/rdma_write_test.dir/src/req_test/write_test.c.i
.PHONY : src/req_test/write_test.c.i

src/req_test/write_test.s: src/req_test/write_test.c.s
.PHONY : src/req_test/write_test.s

# target to generate assembly for a file
src/req_test/write_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdma_write_test.dir/build.make CMakeFiles/rdma_write_test.dir/src/req_test/write_test.c.s
.PHONY : src/req_test/write_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ibv_devices"
	@echo "... ibv_devinfo"
	@echo "... rdma_atomic_test"
	@echo "... rdma_client"
	@echo "... rdma_cm_client"
	@echo "... rdma_cm_server"
	@echo "... rdma_read_test"
	@echo "... rdma_send_test"
	@echo "... rdma_server"
	@echo "... rdma_write_test"
	@echo "... src/common/common.o"
	@echo "... src/common/common.i"
	@echo "... src/common/common.s"
	@echo "... src/common/rdma_common.o"
	@echo "... src/common/rdma_common.i"
	@echo "... src/common/rdma_common.s"
	@echo "... src/device/ibv_devices_test.o"
	@echo "... src/device/ibv_devices_test.i"
	@echo "... src/device/ibv_devices_test.s"
	@echo "... src/device/ibv_devinfo_test.o"
	@echo "... src/device/ibv_devinfo_test.i"
	@echo "... src/device/ibv_devinfo_test.s"
	@echo "... src/req_test/atomic_test.o"
	@echo "... src/req_test/atomic_test.i"
	@echo "... src/req_test/atomic_test.s"
	@echo "... src/req_test/rdma_client.o"
	@echo "... src/req_test/rdma_client.i"
	@echo "... src/req_test/rdma_client.s"
	@echo "... src/req_test/rdma_cm/rdma_cm_client.o"
	@echo "... src/req_test/rdma_cm/rdma_cm_client.i"
	@echo "... src/req_test/rdma_cm/rdma_cm_client.s"
	@echo "... src/req_test/rdma_cm/rdma_cm_server.o"
	@echo "... src/req_test/rdma_cm/rdma_cm_server.i"
	@echo "... src/req_test/rdma_cm/rdma_cm_server.s"
	@echo "... src/req_test/rdma_server.o"
	@echo "... src/req_test/rdma_server.i"
	@echo "... src/req_test/rdma_server.s"
	@echo "... src/req_test/read_test.o"
	@echo "... src/req_test/read_test.i"
	@echo "... src/req_test/read_test.s"
	@echo "... src/req_test/send_test.o"
	@echo "... src/req_test/send_test.i"
	@echo "... src/req_test/send_test.s"
	@echo "... src/req_test/write_test.o"
	@echo "... src/req_test/write_test.i"
	@echo "... src/req_test/write_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

